# Ejecución dentro de docker compose (nombres de servicio de la red interna)
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${PAYMENT_DB_NAME:payment_db}
  kafka:
    bootstrap-servers: kafka:9092
